name: GitHub Actions Demo
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }}."
      - run: echo "🔎 The name of your target branch is ${{ github.base_ref }}."
      - name: Check out code.
        uses: actions/checkout@v3
      - run: git log "${{ github.base_ref }}.."
      - run: cargo install conventional_commits_linter
      - run: RUST_LOG=trace conventional_commits_linter --allow-angular-type-only --from-reference "${{ github.base_ref }}"
