name: GitHub Actions Demo
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: git show-ref
      - run: git log
      - run: cargo install conventional_commits_linter
      - run: RUST_LOG=trace conventional_commits_linter --allow-angular-type-only --from-reference "origin/${{ github.head_ref }}"
